### ISSUE TITLE
Unable to run from within a container

### ISSUE THREAD

**Issue by ggirard07** [blackducksoftware/detect-ado#51]
By default, the task try to download the detect script to `$(Agent.WorkFolder)/detect`, but when running a pipeline task in a container `$(Agent.WorkFolder)` seems to be mounted as readonly, which prevent the task to create the `detect` folder.

Logs from within the container itself:
```bash
mkdir: cannot create directory '/__w/detect': Permission denied
```

Default `docker create` command used by ADO:
```bash
/usr/bin/docker create --name jre_container_mcrmicrosoftcomjavajre17zuluubuntu_f5c0ad --label ed5396 \
--network vsts_network_0dc13f81572c44a98167d17236bfcb8c  \
-v "/var/run/docker.sock":"/var/run/docker.sock" \
-v "/home/rd/Agents/agent0/_work/13":"/__w/13" \
-v "/home/rd/Agents/agent0/_work/_temp":"/__w/_temp" \
-v "/home/rd/Agents/agent0/_work/_tasks":"/__w/_tasks" \
-v "/home/rd/Agents/agent0/_work/_tool":"/__t" \
-v "/home/rd/Agents/agent0/externals":"/__a/externals":ro \
-v "/home/rd/Agents/agent0/_work/.taskkey":"/__w/.taskkey" \
mcr.microsoft.com/java/jre:17-zulu-ubuntu
```

As only the `detect` folder can currently be configured - and not the entire path - my only workaround is to mount the expected path `$(Agent.WorkFolder)` manually to ensure read/write access when creating the container reference:
```yaml
resources:
  containers:
    - container: detect_container
      image: my_container:latest
      volumes:
        - $(Agent.WorkFolder):/__w
```
